fluxboxlauncher                                usr/bin

flxl/*.py                                      usr/lib/python3/dist-packages/flxl
flxl/lib/*.py                                  usr/lib/python3/dist-packages/flxl/lib

fluxboxlauncher.svg                            usr/share/icons/hicolor/scalable/apps

ressources/*.svg                               usr/share/fluxboxlauncher/icons/default

flxl/locale/fr/LC_MESSAGES/fluxboxlauncher.mo  usr/share/locale/fr/LC_MESSAGES

fluxboxlauncher.desktop                        usr/share/applications
